/** Static color pixels for the startup tree; "." is transparent. */
export const PALETTE: Record<string, string> = {
  A: "#2a6b73",
  B: "#36807b",
  C: "#469c85",
  D: "#489577",
  E: "#5b3c3e",
  F: "#5caa75",
  G: "#6b433f",
  H: "#6faf69",
  I: "#734941",
  J: "#7a4b43",
  K: "#7abc68",
  L: "#88bd69",
  M: "#aaa05d",
  N: "#b0cc5d",
  O: "#c98a57",
  P: "#cc925a",
  Q: "#d5ae64",
  R: "#e8bc66",
  S: "#d45d5a", // π fruit
};

export const TREE: readonly string[] = [
  "................................................",
  "................................................",
  ".....................N.KKHRNKK..................",
  "................NNNNRKNN.HKKNHK.................",
  "...............RNHKNNNHNNKNNHHNHKKHK............",
  "..........NKNHHHHNKNKKNHHKNKKHKKHKNKHH..........",
  ".........KHK..NNKHKNHKKKKKKHKKHNHNHKKHN.........",
  ".........NHHSSSSSKHKKNNKHHNHNHRNHNNRNHR.........",
  "........LFFCLSCSLLCFFFCLCFQLFCLLFFFCFFF.C.......",
  ".........LLCCSLSFFQLCFCCSSSSSLFCFCQCFCF.CFC.....",
  "........CCCLLCFFLFFFLLCLLSLSCLFLCFCCCLQCCCL.....",
  ".........CLLLFLCCLLQCQCLCSCSFFCLCCCFFLLFLFFL....",
  ".......CFFCFLFFFFCLFLFLC.CCLFCCCLFCLFFFCFCCC....",
  "......LFQCFFLCFCFCLLCLCCLCCLLLCFFLFLFLFFC.FL....",
  ".....BBBMBDAAABBDDDADBBDBABABDBBDBDDABBBBADA....",
  ".....DDABDADDDAABAADDBIAADBAAABABBBBDBBAADBA....",
  ".....AAD.BDDAAABBDDBAAADAAMDBBDDBBDDABBDADDB....",
  ".....BBBBDBBAABDABDABAABDAABAAADBBDBBBDADBDBA...",
  "....DADDBADADAABDBIIIIAD..II.D..ABAABBAAAABBB...",
  "....BAABABBDIIBAAB.AIIIIM.IAD..IDD.D.DADBDDBA...",
  ".....ADDBBBIIIIIII..IIII..II..III...IIIIIIIII...",
  "..............IIIII.IIII..II..II..IIISSSSSII....",
  "................IIIP.IIIIPII.III.PIIIIS.S.......",
  ".................IIIP.IJJPEIIIIIPII...S.S.......",
  "...................IIPIJJPEEIIIPII..............",
  "....................IPIJJPEEIIPI................",
  ".....................IPJJPEEIPI.................",
  ".....................IIPJPEEPI..................",
  "......................IPJPEEP...................",
  ".......................IJPEE....................",
  ".......................JPPEP....................",
  "......................GJPPEPE...................",
  "......................GJPPEPE...................",
  "......................GPJPEPEG..................",
  ".....................GGPJPEEEG..................",
  "....................GGGOJPEEOEG.................",
  ".......S..........GGGGOJJPEEPOGGG...............",
  ".......SSS......GGGGGOPJJPEEPEGOGGG.............",
  ".......S......GGGGGOOGJJJPEEEEGGOOGGGG.SSSSS....",
  ".......SSS...GGOOGGGG.........GGGGGOOGG.S.S.....",
  ".......S......GG..G..............G..GG...S.S....",
  "................................................",
  "................................................",
];

export const SMALL_TREE: readonly string[] = [
  "..............................",
  ".............NKKRKK...........",
  "..........NNRKN.KNH...........",
  "......NNHHHKKKHHNKHKHNHH......",
  "......HNHHHHKNKHNNHNHNNH......",
  ".....LFSSSSSFFLCQFCLFFFF.C....",
  ".....CCLSFSFLLLLLCLLCCCLCCL...",
  "......LLSCSLCQLCCFFLCCFLFLF...",
  "....FQFLCCFLCLCLCLLFFFFLFCF...",
  "...DABADDABADBAABAAABBDBAAB...",
  "...AD.DAABBDAADAMBBDBDABDAD...",
  "..DADBDDABDIIID.I.D.AABSSSSS..",
  "..BABABIIAA.IIIMID.ID..DSBSA..",
  ".........IIIIII.I..I.IIISIS...",
  "...........IP.JJEIIIPI........",
  "............IPJJEIIPI.........",
  ".............IJJEIP...........",
  ".............IPJEPI...........",
  "..............IJE.............",
  "..............JPEE............",
  "..............JPEE............",
  ".............GPJEEG...........",
  "............GGOJEOE...........",
  "..........GGGOJJEPEOGG........",
  "...SSSSSGOOGG......GGGOG......",
  ".....S.S.G.G..........GG......",
  "......S.S.....................",
];

export const TINY_TREE: readonly string[] = [
  "....................",
  ".......NRNHKK.......",
  "....NHHKKNKKKHNH....",
  "....SSSSSNHHRHNH....",
  "...CCSFSLCFFFCCLCL..",
  "...FCSFSLLCLCLCFCC..",
  "..BMDABDDBAABDDBBD..",
  "..A.DABDAAADDBDBDD..",
  "..AABIA.II.ASSSSSDA.",
  "......IIII.IISISII..",
  ".......IPIPIISIS....",
  ".........PPEI.......",
  ".........IPE........",
  "..........PP........",
  ".........GPP........",
  "........GGPEG.......",
  ".SSSSS.GGPPEGGG.....",
  "...S.SOGG...GGGG....",
  "....S.S.............",
];
